CREATE PROCEDURE SPD_LIMPEZA_TABELAS(
	 @TABELA		VARCHAR(100)
	,@QUANTIDADE	INT
	,@DIAS			INT
)
AS
BEGIN
	EXECUTE(
			'DELETE TOP ('+ @QUANTIDADE +') FROM ' + 
					@TABELA + ' WHERE DH_TIMESTAMP <= DATEADD(DAY,'+@DIAS+',GETDATE())')
END

